select_origin: directory
files_origin: "."
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: ""
history: true
focus_max: 2
record_types:
  undefined:
    fill: "#858585"
    stroke: "#858585"
  echo:
    fill: "#df8e1d"
    stroke: "#df8e1d"
  region:
    fill: "#4c4f69"
    stroke: "#4c4f69"
  rotImmune:
    fill: "#40a02b"
    stroke: "#40a02b"
  startingRegion:
    fill: "#04a5e5"
    stroke: "#04a5e5"
  rotted:
    fill: "#d20f39"
    stroke: "#d20f39"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
references_as_nodes: false
references_type_label: references
record_filters: []
graph_background_color: "#eff1f5"
graph_highlight_color: "#ea76cb"
graph_highlight_on_hover: true
graph_text_size: 10
graph_arrows: true
node_size_method: unique
node_size: 4
node_size_max: 20
node_size_min: 2
attraction_force: 600
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
record_metas: []
generate_id: always
link_context: tooltip
hide_id_from_record_header: false
title: "Watcher Region Map"
author: "shrubfromtomorrow"
description: "A region connection map for Rain World: The Watcher"
keywords: []
link_symbol: ""
csl: ""
bibliography: ""
csl_locale: ""
css_custom: ""
devtools: false
lang: en
